cert: |
  -----BEGIN CERTIFICATE-----
  MIIEADCCAuigAwIBAgIUccgewpn9pppYY+B6BrkdFaPe5K0wDQYJKoZIhvcNAQEL
  BQAwgZ0xCzAJBgNVBAYTAlVLMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxv
  bmRvbjEVMBMGA1UECgwMSW5hbnp6eiBMdGQuMSEwHwYDVQQLDBhJbmZvcm1hdGlv
  biBUZWNobm9sb2dpZXMxHjAcBgkqhkiG9w0BCQEWD2VtYWlsQGVtYWlsLmNvbTES
  MBAGA1UEAwwJbG9jYWxob3N0MB4XDTIxMDczMTAyNDcxMFoXDTI2MDczMDAyNDcx
  MFowgZ0xCzAJBgNVBAYTAlVLMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxv
  bmRvbjEVMBMGA1UECgwMSW5hbnp6eiBMdGQuMSEwHwYDVQQLDBhJbmZvcm1hdGlv
  biBUZWNobm9sb2dpZXMxHjAcBgkqhkiG9w0BCQEWD2VtYWlsQGVtYWlsLmNvbTES
  MBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
  AQEAl39Dq1gd3QucpXLezAXK7yS4r/PKlwPrkrkeAg7OVsDe2qjwpRtDs5j7u0he
  HLbIDvZIDGW1B8+RfnwJyL/B7gl4iZN5dpky9S5MO1PpC+LLDBRIM8o7wg/QvBj1
  OnQutUOJh8WP7UGBpTOpZVE059MR4ijle2dfb/Fz2dGLIPe8H8UXk2qBXwj7UGz+
  s7++7sYa6J10t/L3ZtVchkH1cUpDFXVmiBN0qEvfmZY1ODNwgPJSDpnxo4N2pvnj
  RcPDzsJxUhkbkE1YTxoqG9OpFHi2e9//LuHFFHMCZXV9KD4Bno7SwHgNC2piddlc
  5hSxR92BSwbV04FGoW6emjPUuQIDAQABozYwNDAyBgNVHREEKzApgglsb2NhbGhv
  c3SCC2luYW56enouY29tgg93d3cuaW5hbnp6ei5jb20wDQYJKoZIhvcNAQELBQAD
  ggEBAAaRxrlF5ZnTTWxluUHWW6TrNR2bQaxuAKbrcDUT4IE8AASLjPpx3cYQ2N7h
  B8FpKLnbyTUJe4MM6PDo2aT0KqQIofA/2Xmdfk41viEmK8gnzrQ0faqYOKyyPqLP
  18iYAeAa2uBPetL6EWYIKpeU5NUKLRs+dhUbdgmE0quqOAfQSAKeIbBBQ79pIWH5
  rov386+M7TxBfwJDvw5JB3s3gqecOVwn6kUOxLew3zoo2Q88NwGpz2joWfVMY4+f
  5aC1/m1ii70QD9S0ie4bWOrhYNy7wm9bj5Pba+MXk9C8bYlLHqsSHAhLU5KogF/M
  qRj+warKao9lqAOOtPCvKoCorXc=
  -----END CERTIFICATE-----
